var gate = HandDriveGate()
var time = 10.0
func sample(_ ratio: Double, x: Double = 0.5, y: Double = 0.5, aspect: Double = 0.75, age: Double = 0, enabled: Bool = true) -> HandDecision {
    time += 0.1
    return gate.evaluate(HandSample(pinchX: x, pinchY: y, imageAspect: aspect, pinchRatio: ratio, capturedAt: time - age), now: time, enabled: enabled)
}
func grab() {
    assert(!sample(1.1).held)
    assert(!sample(0.2).held)
    assert(!sample(0.2).held)
    let d = sample(0.2)
    assert(d.held && !d.moving, "Grab at centre must not drive")
}
assert(!sample(0.2).held, "Open fingers before first grab")
grab()
assert(sample(0.6).held, "Pinch hysteresis")
let forward = sample(0.2, y: 0.70)
assert(forward.forward > 0 && forward.steering == 0)
let reverse = sample(0.2, y: 0.30)
assert(reverse.moving && reverse.forward < 0 && reverse.steering == 0)
let left = sample(0.2, x: 0.25)
let right = sample(0.2, x: 0.75)
assert(left.moving && left.steering < 0 && left.forward == 0)
assert(right.moving && right.steering == -left.steering)
let diagonal = sample(0.2, x: 1, y: 1)
assert(abs(hypot(diagonal.stickX, diagonal.stickY) - 1) < 0.00001)
assert(hypot(diagonal.steering, diagonal.forward) <= 0.850001)
let centre = sample(0.2, x: 0.53, y: 0.51)
assert(centre.held && !centre.moving, "Deadzone ignores small hand jitter")
assert(!sample(0.75).held, "Release stops and removes highlight")
assert(!sample(0.2, x: 0.75).held)
assert(!sample(0.2, x: 0.75).held)
assert(!sample(0.2, x: 0.75).held, "Cannot grab away from centre")
grab()
assert(!gate.evaluate(nil, now: time, enabled: true).held)
assert(!sample(0.2, y: 0.70).held, "After tracking loss must return to centre")
assert(!sample(0.2).held)
assert(!sample(0.2).held)
assert(sample(0.2).held)
assert(!gate.evaluate(nil, now: time + 0.7, enabled: true).held)
time += 0.7
assert(!sample(0.2).held, "Sustained loss requires opening again")
grab()
assert(!sample(0.2, age: 0.31).held)
assert(!sample(0.2).held)
grab()
assert(!sample(0.2, enabled: false).held)
assert(!sample(0.2).held)
grab()
time += 1
assert(!sample(0.2).held)
grab()
assert(!sample(0.2, age: 0.15).held)
for invalid in [Double.nan, Double.infinity, -Double.infinity] {
    assert(!sample(invalid).held)
    assert(!sample(0.2, x: invalid).held)
    assert(!sample(0.2, y: invalid).held)
    assert(!sample(0.2, aspect: invalid).held)
}
assert(!sample(0.2, aspect: 0).held)
assert(!sample(0.2, age: -1).held)
func mix(_ d: HandDecision) -> (Int, Int) {
    RoverMix.motors(x: d.steering, y: d.forward, limit: 0.35, swap: false, reverse1: false, reverse3: false)
}
let lm = mix(left), rm = mix(right), fm = mix(forward), bm = mix(reverse)
assert(lm.0 < 0 && lm.1 > 0 && rm.0 == lm.1 && rm.1 == lm.0)
assert(fm.0 > 0 && fm.0 == fm.1 && bm.0 < 0 && bm.0 == bm.1)
print("PASS: centre-only grab/highlight, deadzone, four directions, diagonal clamp, motor mixing, release/loss stop, stale frames and rearming")

for size in [CGSize(width: 640, height: 480), CGSize(width: 480, height: 640), CGSize(width: 720, height: 720)] {
    for aspect in [0.46, 0.75, 1.0, 1.8] {
        let crop = CameraFraming.crop(source: size, aspect: aspect)
        assert(abs(crop.width / crop.height - aspect) < 0.00001)
        assert(abs(crop.midX - size.width / 2) < 0.00001)
        assert(abs(crop.midY - size.height / 2) < 0.00001)
        assert(crop.width <= size.width && crop.height <= size.height)
    }
}
assert(CameraFraming.crop(source: .zero, aspect: 0.5) == .zero)
assert(CameraFraming.crop(source: CGSize(width: 640, height: 480), aspect: .nan) == .zero)
print("PASS: shared camera crop preserves centred joystick coordinates across sensor/view aspect ratios")

let sensor = CGSize(width: 720, height: 720)
let portraitCrop = CameraFraming.crop(source: sensor, aspect: 0.5)
let mappedCentre = CameraFraming.project(CGPoint(x: 0.5, y: 0.5), source: sensor, crop: portraitCrop)
assert(mappedCentre == CGPoint(x: 0.5, y: 0.5))
let mappedLeft = CameraFraming.project(CGPoint(x: 0.35, y: 0.5), source: sensor, crop: portraitCrop)
let mappedRight = CameraFraming.project(CGPoint(x: 0.65, y: 0.5), source: sensor, crop: portraitCrop)
assert(abs(mappedLeft.x + mappedRight.x - 1) < 0.00001)
assert(mappedLeft.x < 0.5 && mappedRight.x > 0.5)
var scaleTracker = FingerScaleTracker()
assert(scaleTracker.update(nil, now: 0) == nil)
assert(scaleTracker.update(100, now: 1) == 100)
assert(scaleTracker.update(nil, now: 1.2) == 100)
assert(scaleTracker.update(20, now: 1.3) == 100)
assert(scaleTracker.update(nil, now: 1.41) == nil)
assert(scaleTracker.update(80, now: 1.5) == 80)
scaleTracker.reset()
assert(scaleTracker.update(nil, now: 1.6) == nil)
print("PASS: full-frame landmark mapping is symmetric; scale cache rejects outliers and expires after 400 ms")
