// Runs the real BluetoothLink state machine with only the BLE transport stubbed.
func connectedLink() -> BluetoothLink {
    let link = BluetoothLink()
    link.ready = true
    link.send("HELLO")
    link.receiveReplyLine("ROVER:1")
    assert(link.roverCompatible && !link.armed && link.testSent == ["HELLO"])
    return link
}
let link = connectedLink()
link.setVoiceMode(true)
link.receiveReplyLine("OK:STOP")
let f = VoiceCommand(direction: .forward, small: false)
link.receiveVoiceCommand(f)
assert(link.testSent.last == "ARM" && !link.armed && link.motor1 == 0)
link.receiveReplyLine("OK:ARM")
assert(link.armed && link.motor1 > 0 && link.motor3 > 0)
link.tick()
assert(link.testSent.last?.hasPrefix("D:") == true)
link.receiveReplyLine("OK:D")
// Simulate the real deadline elapsing without waiting five wall-clock seconds.
_ = link.voiceMotion.start(f, now: ProcessInfo.processInfo.systemUptime - 6, enabled: true)
link.tick()
assert(link.motor1 == 0 && link.motor3 == 0 && link.testSent.last == "D:0:0")
link.receiveReplyLine("OK:D")
link.receiveVoiceCommand(VoiceCommand(direction: .left, small: false))
assert(link.motor1 < 0 && link.motor3 > 0, "Second voice command must move after first completes")
link.emergencyStop()
assert(!link.armed && link.motor1 == 0)
link.receiveReplyLine("OK:STOP")
link.receiveVoiceCommand(VoiceCommand(direction: .right, small: false))
assert(link.testSent.last == "ARM")
link.receiveReplyLine("OK:ARM")
assert(link.motor1 > 0 && link.motor3 < 0, "Fresh command after Stop must automatically arm")
link.receiveReplyLine("SAFE:BUTTON")
assert(!link.armed && link.motor1 == 0 && link.pendingDrive.input == nil)

let manual = connectedLink()
let gesture = UUID()
manual.moveJoystick(CGSize(width: 0, height: -1), gesture: gesture)
assert(manual.testSent.last == "ARM")
manual.releaseJoystick()
manual.receiveReplyLine("OK:ARM")
assert(!manual.armed && manual.motor1 == 0 && manual.testSent.last == "STOP", "Release before ARM reply must stop")
manual.receiveReplyLine("OK:STOP")
manual.moveJoystick(CGSize(width: 0, height: -1), gesture: gesture)
assert(manual.testSent.last == "STOP", "Old gesture must not resume after stop")
manual.moveJoystick(CGSize(width: 0, height: -1), gesture: UUID())
manual.receiveReplyLine("OK:ARM")
assert(manual.motor1 > 0, "New joystick gesture automatically arms")
manual.emergencyStop()
manual.receiveReplyLine("OK:STOP")
manual.moveJoystick(CGSize(width: 1, height: 0), gesture: UUID())
manual.pendingDrive.set(CGSize(width: 1, height: 0), voice: nil, now: ProcessInfo.processInfo.systemUptime - 1)
manual.receiveReplyLine("OK:ARM")
assert(!manual.armed && manual.motor1 == 0, "Expired input cannot start when ARM arrives late")

let hand = connectedLink()
hand.setHandMode(true)
hand.handInputActive = true
hand.receiveReplyLine("OK:STOP")
var t = ProcessInfo.processInfo.systemUptime
func handSample(_ ratio: Double, x: Double = 0.5) {
    t = ProcessInfo.processInfo.systemUptime
    hand.receiveHandSample(HandSample(pinchX: x, pinchY: 0.5, imageAspect: 0.75, pinchRatio: ratio, capturedAt: t))
}
handSample(1.1)
handSample(0.2)
Thread.sleep(forTimeInterval: 0.17)
handSample(0.2)
handSample(0.2, x: 0.7)
assert(hand.testSent.last == "ARM", "Fresh hand gesture automatically arms")
hand.receiveReplyLine("OK:ARM")
assert(hand.motor1 > 0 && hand.motor3 < 0)
hand.emergencyStop()
hand.receiveReplyLine("OK:STOP")
handSample(0.2, x: 0.7)
assert(hand.motor1 == 0 && hand.testSent.last == "STOP", "Held pinch cannot restart after Stop")
print("PASS: real BluetoothLink automatic arming, consecutive voice commands, timed stop, stop/release during ARM, stale acknowledgement rejection, joystick/hand fresh-input requirements")

let inactive = connectedLink()
inactive.setControlsActive(false)
inactive.receiveReplyLine("OK:STOP")
inactive.moveJoystick(CGSize(width: 0, height: -1), gesture: UUID())
inactive.tick()
assert(inactive.testSent.last == "STOP" && inactive.pendingDrive.input == nil, "Background callbacks cannot auto-arm")
inactive.setControlsActive(true)
inactive.moveJoystick(CGSize(width: 0, height: -1), gesture: UUID())
assert(inactive.testSent.last == "ARM")
print("PASS: inactive/background control input is blocked")
